# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# [].tap do |array|
#   100.times do |i|
#     created_at = Time.current

#     array << {
#       title: "This is #{i+1} Article",
#       text: "Hello This is #{i+1} Text",
#       created_at: created_at,
#       updated_at: created_at
#     }
#   end

#   result = Article.insert_all array
#   puts result.inspect

created_at = Time.current
result = Article.insert_all(
  [
    {"title":"Geological Engineer","text":"orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", created_at: created_at,updated_at: created_at},
    {"title":"Registered Nurse","text":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",created_at: created_at,updated_at: created_at},
    {"title":"Statistician III","text":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",created_at: created_at,updated_at: created_at},
    {"title":"Web Developer III","text":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien",created_at: created_at,updated_at: created_at},
    {"title":"Programmer Analyst IV","text":"sapien sapien non mi integer ac neque duis bibendum morbi",created_at: created_at,updated_at: created_at},
    {"title":"Computer Systems Analyst II","text":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Marketing Assistant","text":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget",created_at: created_at,updated_at: created_at},
    {"title":"Analog Circuit Design manager","text":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa",created_at: created_at,updated_at: created_at},
    {"title":"Operator","text":"elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo",created_at: created_at,updated_at: created_at},
    {"title":"Biostatistician IV","text":"proin leo odio porttitor id consequat in consequat ut nulla",created_at: created_at,updated_at: created_at},
    {"title":"Food Chemist","text":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",created_at: created_at,updated_at: created_at},
    {"title":"Administrative Assistant IV","text":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",created_at: created_at,updated_at: created_at},
    {"title":"Electrical Engineer","text":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",created_at: created_at,updated_at: created_at},
    {"title":"Civil Engineer","text":"leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",created_at: created_at,updated_at: created_at},
    {"title":"Software Engineer II","text":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",created_at: created_at,updated_at: created_at},
    {"title":"GIS Technical Architect","text":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",created_at: created_at,updated_at: created_at},
    {"title":"Product Engineer","text":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",created_at: created_at,updated_at: created_at},
    {"title":"Staff Accountant IV","text":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",created_at: created_at,updated_at: created_at},
    {"title":"Chief Design Engineer","text":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",created_at: created_at,updated_at: created_at},
    {"title":"Payment Adjustment Coordinator","text":"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",created_at: created_at,updated_at: created_at},
    {"title":"Nuclear Power Engineer","text":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",created_at: created_at,updated_at: created_at},
    {"title":"Data Coordiator","text":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",created_at: created_at,updated_at: created_at},
    {"title":"Financial Advisor","text":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Geological Engineer","text":"orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", created_at: created_at,updated_at: created_at},
    {"title":"Registered Nurse","text":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",created_at: created_at,updated_at: created_at},
    {"title":"Statistician III","text":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",created_at: created_at,updated_at: created_at},
    {"title":"Web Developer III","text":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien",created_at: created_at,updated_at: created_at},
    {"title":"Programmer Analyst IV","text":"sapien sapien non mi integer ac neque duis bibendum morbi",created_at: created_at,updated_at: created_at},
    {"title":"Computer Systems Analyst II","text":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Marketing Assistant","text":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget",created_at: created_at,updated_at: created_at},
    {"title":"Analog Circuit Design manager","text":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa",created_at: created_at,updated_at: created_at},
    {"title":"Operator","text":"elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo",created_at: created_at,updated_at: created_at},
    {"title":"Biostatistician IV","text":"proin leo odio porttitor id consequat in consequat ut nulla",created_at: created_at,updated_at: created_at},
    {"title":"Food Chemist","text":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",created_at: created_at,updated_at: created_at},
    {"title":"Administrative Assistant IV","text":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",created_at: created_at,updated_at: created_at},
    {"title":"Electrical Engineer","text":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",created_at: created_at,updated_at: created_at},
    {"title":"Civil Engineer","text":"leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",created_at: created_at,updated_at: created_at},
    {"title":"Software Engineer II","text":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",created_at: created_at,updated_at: created_at},
    {"title":"GIS Technical Architect","text":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",created_at: created_at,updated_at: created_at},
    {"title":"Product Engineer","text":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",created_at: created_at,updated_at: created_at},
    {"title":"Staff Accountant IV","text":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",created_at: created_at,updated_at: created_at},
    {"title":"Chief Design Engineer","text":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",created_at: created_at,updated_at: created_at},
    {"title":"Payment Adjustment Coordinator","text":"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",created_at: created_at,updated_at: created_at},
    {"title":"Nuclear Power Engineer","text":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",created_at: created_at,updated_at: created_at},
    {"title":"Data Coordiator","text":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",created_at: created_at,updated_at: created_at},
    {"title":"Financial Advisor","text":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Geological Engineer","text":"orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", created_at: created_at,updated_at: created_at},
    {"title":"Registered Nurse","text":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",created_at: created_at,updated_at: created_at},
    {"title":"Statistician III","text":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",created_at: created_at,updated_at: created_at},
    {"title":"Web Developer III","text":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien",created_at: created_at,updated_at: created_at},
    {"title":"Programmer Analyst IV","text":"sapien sapien non mi integer ac neque duis bibendum morbi",created_at: created_at,updated_at: created_at},
    {"title":"Computer Systems Analyst II","text":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Marketing Assistant","text":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget",created_at: created_at,updated_at: created_at},
    {"title":"Analog Circuit Design manager","text":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa",created_at: created_at,updated_at: created_at},
    {"title":"Operator","text":"elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo",created_at: created_at,updated_at: created_at},
    {"title":"Biostatistician IV","text":"proin leo odio porttitor id consequat in consequat ut nulla",created_at: created_at,updated_at: created_at},
    {"title":"Food Chemist","text":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",created_at: created_at,updated_at: created_at},
    {"title":"Administrative Assistant IV","text":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",created_at: created_at,updated_at: created_at},
    {"title":"Electrical Engineer","text":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",created_at: created_at,updated_at: created_at},
    {"title":"Civil Engineer","text":"leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",created_at: created_at,updated_at: created_at},
    {"title":"Software Engineer II","text":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",created_at: created_at,updated_at: created_at},
    {"title":"GIS Technical Architect","text":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",created_at: created_at,updated_at: created_at},
    {"title":"Product Engineer","text":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",created_at: created_at,updated_at: created_at},
    {"title":"Staff Accountant IV","text":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",created_at: created_at,updated_at: created_at},
    {"title":"Chief Design Engineer","text":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",created_at: created_at,updated_at: created_at},
    {"title":"Payment Adjustment Coordinator","text":"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",created_at: created_at,updated_at: created_at},
    {"title":"Nuclear Power Engineer","text":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",created_at: created_at,updated_at: created_at},
    {"title":"Data Coordiator","text":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",created_at: created_at,updated_at: created_at},
    {"title":"Financial Advisor","text":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Geological Engineer","text":"orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", created_at: created_at,updated_at: created_at},
    {"title":"Registered Nurse","text":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",created_at: created_at,updated_at: created_at},
    {"title":"Statistician III","text":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",created_at: created_at,updated_at: created_at},
    {"title":"Web Developer III","text":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien",created_at: created_at,updated_at: created_at},
    {"title":"Programmer Analyst IV","text":"sapien sapien non mi integer ac neque duis bibendum morbi",created_at: created_at,updated_at: created_at},
    {"title":"Computer Systems Analyst II","text":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Marketing Assistant","text":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget",created_at: created_at,updated_at: created_at},
    {"title":"Analog Circuit Design manager","text":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa",created_at: created_at,updated_at: created_at},
    {"title":"Operator","text":"elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo",created_at: created_at,updated_at: created_at},
    {"title":"Biostatistician IV","text":"proin leo odio porttitor id consequat in consequat ut nulla",created_at: created_at,updated_at: created_at},
    {"title":"Food Chemist","text":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",created_at: created_at,updated_at: created_at},
    {"title":"Administrative Assistant IV","text":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",created_at: created_at,updated_at: created_at},
    {"title":"Electrical Engineer","text":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",created_at: created_at,updated_at: created_at},
    {"title":"Civil Engineer","text":"leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",created_at: created_at,updated_at: created_at},
    {"title":"Software Engineer II","text":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",created_at: created_at,updated_at: created_at},
    {"title":"GIS Technical Architect","text":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",created_at: created_at,updated_at: created_at},
    {"title":"Product Engineer","text":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",created_at: created_at,updated_at: created_at},
    {"title":"Staff Accountant IV","text":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",created_at: created_at,updated_at: created_at},
    {"title":"Chief Design Engineer","text":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",created_at: created_at,updated_at: created_at},
    {"title":"Payment Adjustment Coordinator","text":"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",created_at: created_at,updated_at: created_at},
    {"title":"Nuclear Power Engineer","text":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",created_at: created_at,updated_at: created_at},
    {"title":"Data Coordiator","text":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",created_at: created_at,updated_at: created_at},
    {"title":"Financial Advisor","text":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Geological Engineer","text":"orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", created_at: created_at,updated_at: created_at},
    {"title":"Registered Nurse","text":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",created_at: created_at,updated_at: created_at},
    {"title":"Statistician III","text":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",created_at: created_at,updated_at: created_at},
    {"title":"Web Developer III","text":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien",created_at: created_at,updated_at: created_at},
    {"title":"Programmer Analyst IV","text":"sapien sapien non mi integer ac neque duis bibendum morbi",created_at: created_at,updated_at: created_at},
    {"title":"Computer Systems Analyst II","text":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Marketing Assistant","text":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget",created_at: created_at,updated_at: created_at},
    {"title":"Analog Circuit Design manager","text":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa",created_at: created_at,updated_at: created_at},
    {"title":"Operator","text":"elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo",created_at: created_at,updated_at: created_at},
    {"title":"Biostatistician IV","text":"proin leo odio porttitor id consequat in consequat ut nulla",created_at: created_at,updated_at: created_at},
    {"title":"Food Chemist","text":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",created_at: created_at,updated_at: created_at},
    {"title":"Administrative Assistant IV","text":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",created_at: created_at,updated_at: created_at},
    {"title":"Electrical Engineer","text":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",created_at: created_at,updated_at: created_at},
    {"title":"Civil Engineer","text":"leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",created_at: created_at,updated_at: created_at},
    {"title":"Software Engineer II","text":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",created_at: created_at,updated_at: created_at},
    {"title":"GIS Technical Architect","text":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",created_at: created_at,updated_at: created_at},
    {"title":"Product Engineer","text":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",created_at: created_at,updated_at: created_at},
    {"title":"Staff Accountant IV","text":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",created_at: created_at,updated_at: created_at},
    {"title":"Chief Design Engineer","text":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",created_at: created_at,updated_at: created_at},
    {"title":"Payment Adjustment Coordinator","text":"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",created_at: created_at,updated_at: created_at},
    {"title":"Nuclear Power Engineer","text":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",created_at: created_at,updated_at: created_at},
    {"title":"Data Coordiator","text":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",created_at: created_at,updated_at: created_at},
    {"title":"Financial Advisor","text":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Geological Engineer","text":"orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris", created_at: created_at,updated_at: created_at},
    {"title":"Registered Nurse","text":"vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",created_at: created_at,updated_at: created_at},
    {"title":"Statistician III","text":"primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat",created_at: created_at,updated_at: created_at},
    {"title":"Web Developer III","text":"tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien",created_at: created_at,updated_at: created_at},
    {"title":"Programmer Analyst IV","text":"sapien sapien non mi integer ac neque duis bibendum morbi",created_at: created_at,updated_at: created_at},
    {"title":"Computer Systems Analyst II","text":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum",created_at: created_at,updated_at: created_at},
    {"title":"Marketing Assistant","text":"ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget",created_at: created_at,updated_at: created_at},
    {"title":"Analog Circuit Design manager","text":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa",created_at: created_at,updated_at: created_at},
    {"title":"Operator","text":"elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo",created_at: created_at,updated_at: created_at},
    {"title":"Biostatistician IV","text":"proin leo odio porttitor id consequat in consequat ut nulla",created_at: created_at,updated_at: created_at},
    {"title":"Food Chemist","text":"a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",created_at: created_at,updated_at: created_at},
    {"title":"Administrative Assistant IV","text":"maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur",created_at: created_at,updated_at: created_at},
    {"title":"Electrical Engineer","text":"eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in",created_at: created_at,updated_at: created_at},
    {"title":"Civil Engineer","text":"leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam",created_at: created_at,updated_at: created_at},
    {"title":"Software Engineer II","text":"natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel",created_at: created_at,updated_at: created_at},
    {"title":"GIS Technical Architect","text":"ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus",created_at: created_at,updated_at: created_at},
    {"title":"Product Engineer","text":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat",created_at: created_at,updated_at: created_at},
    {"title":"Staff Accountant IV","text":"in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient",created_at: created_at,updated_at: created_at},
    {"title":"Chief Design Engineer","text":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque",created_at: created_at,updated_at: created_at},
    {"title":"Payment Adjustment Coordinator","text":"enim blandit mi in porttitor pede justo eu massa donec dapibus duis at",created_at: created_at,updated_at: created_at},
    {"title":"Nuclear Power Engineer","text":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est",created_at: created_at,updated_at: created_at},
    {"title":"Data Coordiator","text":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",created_at: created_at,updated_at: created_at},
    {"title":"Financial Advisor","text":"eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum",created_at: created_at,updated_at: created_at}
  ]
)


puts Article.count

